"""
SOCsentinel — Validator Agent service.

7th agent in the pipeline. Acts as an Adversarial Critic and Business Risk Analyst.
Audits the Response Playbook for safety and business impact, and generates Sigma Rules.
"""

from typing import Any

from app.core.config import get_settings
from app.core.logger import get_logger
from app.shared.agent_runner import run_agent
from app.shared.llm.client import create_llm_client
from app.shared.llm.prompt_manager import load_prompt

logger = get_logger(__name__)

async def validate_playbook(
    alert_data: dict[str, Any],
    playbook_result: dict[str, Any],
) -> dict[str, Any]:
    """Validate a response playbook and generate a Sigma rule if applicable.

    Args:
        alert_data: Original alert data.
        playbook_result: Playbook generated by Response Planner.

    Returns:
        Validation results including approval status and potential Sigma rule.
    """
    settings = get_settings()
    # Using the 7B model for validation
    llm = create_llm_client(model_name=settings.qwen3_7b_model)
    system_prompt = load_prompt("validator_system")

    user_message = (
        "Review the following alert and proposed response playbook.\n\n"
        f"Alert Data:\n{alert_data}\n\n"
        f"Response Playbook:\n{playbook_result}\n\n"
        "Evaluate the safety and business impact of this playbook. If it isolates critical infrastructure unnecessarily, reject it."
    )

    result = await run_agent(
        agent_name="Validator",
        llm=llm,
        system_prompt=system_prompt,
        user_message=user_message,
    )

    logger.info(
        "Playbook validated",
        is_approved=result.get("is_approved", False),
        has_sigma_rule=bool(result.get("sigma_rule")),
    )

    return result
