"""
SOCsentinel — Response Planner schemas.
"""

from typing import Any

from pydantic import BaseModel, Field


class ResponsePlaybookStep(BaseModel):
    """A single containment step in the response playbook."""

    order: int = Field(description="Step order in the playbook")
    action: str = Field(description="Specific containment action to take")
    tool: str = Field(description="Security tool or system to use")
    risk_level: str = Field(description="Risk level: low|medium|high")
    automated: bool = Field(description="Whether the step is automated")
    details: str = Field(description="Implementation details for the step")


class ResponsePlaybookRequest(BaseModel):
    """Request payload for generating a response playbook."""

    alert_data: dict[str, Any] = Field(description="Original alert payload")
    triage_result: dict[str, Any] = Field(description="L1 triage result")
    evidence_result: dict[str, Any] = Field(description="Evidence collector output")
    mitre_result: dict[str, Any] = Field(description="MITRE ATT&CK mapping output")
    report_result: dict[str, Any] = Field(description="Report writer output")


class ResponsePlaybookOutput(BaseModel):
    """Response playbook generated by the Response Planner agent."""

    playbook_name: str = Field(description="Descriptive name for the playbook")
    priority: str = Field(description="immediate|urgent|standard")
    containment_status: str = Field(description="Current containment status")
    estimated_containment_time: str = Field(description="Estimated containment duration")
    steps: list[ResponsePlaybookStep] = Field(description="Ordered response steps")
    post_incident: list[str] = Field(description="Post-incident recommendations")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score")
